name: schoolcalendar
description: A new Flutter project.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+8

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  shared_preferences: ^2.0.6
  flutter_slidable: ^0.6.0
  flare_flutter: ^3.0.1
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  google_sign_in: ^5.0.4
  cloud_firestore: ^2.3.0
  syncfusion_flutter_datepicker: ^19.2.47
  animated_icon_button: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8

  
flutter:
  fonts: 
    - family: Nunito Sans 
      fonts: 
        - asset: assets/fonts/NunitoSans-Light.ttf
        

  assets: 
     - assets/

  uses-material-design: true

 
